### PR TITLE
Add CI for portability/integration testing with Sage

### PR DESCRIPTION
**Pull request by mkoeppe**
... to make a current build problem on conda-forge (https://trac.sagemath.org/ticket/33054) visible

### CODE REVIEW

**Comment by kimwalisch** [comment]
This is your current error:

```C++
include/min.hpp:47:38: error: static assertion failed: min(A, B): Cannot compare types A and B
```

The ```is_comparable``` check is defined as:

```C++
template <typename A, typename B>
struct is_comparable
{
  enum {
    value = std::is_same<A, B>::value || (
            std::is_integral<A>::value &&
            std::is_integral<B>::value &&
            sizeof(A) >= sizeof(B))
  };
};
```

Primecount uses the nonstandard ```__int128_t``` type which is not supported default by the ```std::is_integral``` trait if I remember correctly. Therefore primecount must be compiled using the ```-std=gnu++11``` (or -std=gnu++14, -std=gnu++17) (when using GCC or Clang) which is usually enabled by default. My guess is that in your build you use e.g. ```-std=c++11``` instead?! Another reason that could explain your build issue is that your compiler is too old and that its ```std::is_integral``` implementation does not work correctly for ```__int128_t``` even with ```-std=gnu++11```.

**Comment by kimwalisch** [comment]
Primecount used to have the following workaround for this issue (https://github.com/kimwalisch/primecount/blob/v5.3/include/int128_t.hpp#L147):

```C++
template <typename T>
struct is_integral
{
  enum
  {
#if !defined(HAVE_INT128_T)
    value = std::is_integral<T>::value
#else
    value = std::is_integral<T>::value ||
            std::is_same<T, int128_t>::value ||
            std::is_same<T, uint128_t>::value
#endif
  };
};
```

I removed this workaround some time ago when both GCC and Clang's ```std::is_integral``` implementation correctly worked with ```int128_t``` by default (with ```-std=gnu++11``` or ```-std=gnu++14```).

**Comment by mkoeppe** [comment]
According to the log (https://github.com/sagemath/sage/runs/4497392130?check_suite_focus=true):
```
Configuring primecount-7.1 with cmake
-- The CXX compiler identification is GNU 9.4.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /opt/conda/bin/x86_64-conda-linux-gnu-c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test libdivide_branchfree
-- Performing Test libdivide_branchfree - Success
-- Performing Test OpenMP
-- Performing Test OpenMP - Success
-- Performing Test mpopcnt
-- Performing Test mpopcnt - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /sage/local/var/tmp/sage/build/primecount-7.1/src

[...]
/opt/conda/bin/x86_64-conda-linux-gnu-c++ -DENABLE_DIV32 -Dlibprimecount_EXPORTS -I/sage/local/var/tmp/sage/build/primecount-7.1/src/include -isystem /sage/local/include -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/include -O3 -DNDEBUG -fPIC -mpopcnt -fopenmp -MD -MT CMakeFiles/libprimecount.dir/src/P2.cpp.o -MF CMakeFiles/libprimecount.dir/src/P2.cpp.o.d -o CMakeFiles/libprimecount.dir/src/P2.cpp.o -c /sage/local/var/tmp/sage/build/primecount-7.1/src/src/P2.cpp
```

The flags come from environment variables set by conda.
```
CXX=/opt/conda/bin/x86_64-conda-linux-gnu-c++
...
CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /opt/conda/include
```

I'd suggest that if correct operation of the code depends on specific flags, your CMake build system should enforce these flags

**Comment by kimwalisch** [comment]
I confirm that the ```-std=c++17``` flag causes the bug and that e.g. ```-std=gnu++17``` should be used instead.

> I'd suggest that if correct operation of the code depends on specific flags, your CMake build system should enforce these flags

This seems like a good idea, however I was unable to implement this idea cleanly in CMake. Ideally the GNU extensions should be enabled if the C++ compiler uses the GNU dialect. CMake supports ```CMAKE_CXX_EXTENSIONS``` however this option only works (in my tests) if the C++ version is hardcoded to a specific version (see last code section) which is not ideal for primecount (as primecount uses recent C++ features if the preprocessor detects that the compiler supports it). I tried adding the following code to primecount's ```CMakeLists.txt``` but it has no effect:

```CMake
# Does not work if compiled with:
# cmake . -DCMAKE_CXX_FLAGS="-std=c++17"
if (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GNU")
    set(CMAKE_CXX_EXTENSIONS ON)
endif()
```

Is it possible to change your build system script to compile primecount with ```-std=gnu++17``` instead of  ```-std=c++17``` or add ```-std=gnu++17``` after ```-std=c++17``` when building for conda (e.g. try ```cmake . -DCMAKE_CXX_FLAGS="-std=gnu++17"```)? Alternatively you could also patch primecount's ```CMakeLists.txt``` using:

```CMake
# Works correctly if compiled with:
# cmake . -DCMAKE_CXX_FLAGS="-std=c++17"
# Compiler flags will be: "-std=c++17 -std=gnu++11 ..."
if (CMAKE_CXX_COMPILER_FRONTEND_VARIANT STREQUAL "GNU")
    set(CMAKE_CXX_STANDARD 11)
    set(CMAKE_CXX_EXTENSIONS ON)
endif()
```

I don't want to add this workaround to primecount as this hardcodes the C++ version which is not ideal. I am open to other suggestions but so far I am not aware of any clean solution that would fix this issue.

**Comment by mkoeppe** [comment]
> I confirm that the `-std=c++17` flag causes the bug and that e.g. `-std=gnu++17` should be used instead (or ideally remove `-std=c++17`, then `-std=gnu++*` is used by default).
> 
> > I'd suggest that if correct operation of the code depends on specific flags, your CMake build system should enforce these flags
> 
> This seems like a good idea, however I was unable to implement this idea cleanly in CMake.

Perhaps @dimpase can help

**Comment by mkoeppe** [comment]
> Is it possible to change your build system script to compile primecount with `-std=gnu++17` instead of `-std=c++17` or add `-std=gnu++17` after `-std=c++17` when building for conda (e.g. try `cmake . -DCMAKE_CXX_FLAGS="-std=gnu++17"`)? 

We prefer not to add such workarounds for broken upstream build systems

**Comment by kimwalisch** [comment]
Of all the workaround discussed so far the ```is_integral```  workaround https://github.com/kimwalisch/primecount/pull/52#issuecomment-998555388 seems to be the best solution so far. This workaround will likely make primecount compatible with the ```-std=c++*``` compiler option.

I am willing to add this workaround to primecount (if this is useful to sagemath), however I would prefer not to do an immediate release just because of this issue. Would this still be helpful to sagemath?

**Comment by mkoeppe** [comment]
> I am willing to add this workaround to primecount (if this is useful to sagemath), however I would prefer not to do an immediate release just because of this issue. Would this still be helpful to sagemath?

Yes, this would still be helpful, as we can easily add upstream commits as patches to sagemath.

**Comment by kimwalisch** [comment]
Unfortunately the  ```is_integral```  workaround I intended to implement has turned out much more complicated than expected. When using GCC & Clang the C++ standard library does not support 128-bit integers if the flag ```-std=c++*``` is used (this option disables the GNU extensions that are otherwise enabled by default). I have identified at least 5 functions (```std::numeric_limits```,  ```std::is_integral```, ```std::is_signed```, ```std::is_unsigned```, ```std::make_unsigned```) that do not work with ```-std=c++*```. Those functions are used all over the place in primecount's code base and would require hundreds of code lines to be modified. It is also a minefield, I cannot rule out that there are other STL functions that do not work either for 128-bit integers and ```-std=c++*```. Therefore I have decided not to implement this workaround.

The other option to fix this issue in primecount would have been to force enabling the GNU extensions in primecount's build system even if the user tries to disable the GNU extensions using the ```-std=c++*``` option. Unfortunately GCC/Clang do not have a ```--gnu-extensions``` flag and CMake's ```CMAKE_CXX_EXTENSIONS``` only works if the C++ version is hardcoded (which is generally a bad idea and in primecount's case will generate suboptimal code as features from recent C++ versions won't be used).

**Hence I have given up and primecount simply cannot be compiled with ```-std=c++*``` (because this disables the GNU extensions which primecount requires for 128-bit integers) and you should use ```-std=gnu++*``` instead** (or use neither ```-std=c++*``` nor ```-std=gnu++*```  in which case ```-std=gnu++*``` will be used by default).

I have looked up [conda's build system code](https://github.com/conda/conda-build/blob/0a6efdcfa02484954e7a3fdf5c2ec4bb3cb6682e/conda_build/jinja_context.py#L416) and found the following comment:

```Python
"compilerflags": {
    # When put into a CDT these should be the base defaults.
    # Package builds can and will change these frequently.
    "CPPFLAGS": "-D_FORTIFY_SOURCE=2",
    "CFLAGS": "-march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe",
    "CXXFLAGS": "-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -O2 -pipe",
    ...
```

So it seems to me that it is possible to change the ```CXXFLAGS``` when building a package/library for conda and that changing the compiler options for specific packages even happens frequently. Hence I suggest for the primecount conda build to modify the ```CXXFLAGS``` flags to e.g. ```CXXFLAGS="${CXXFLAGS} -std=gnu++17"``` which will overwrite the unsupported default ```-std=c++17``` option. Here is a [blog post](http://www.johnlees.me/blog/2018/10/15/creating-a-conda-package-with-compilation-and-dependencies/) where somebody modified the ```CXXFLAGS``` the same way for building the Boost library for conda. (Another option which has the same effect is to compile primecount for conda using: ```cmake . -DCMAKE_CXX_FLAGS="$CXXFLAGS -std=gnu++17"```)

**Comment by dimpase** [comment]
Using `-std=gnu++17` for a library implies the same for a Python extension which uses it - and, for primecount deps, namely primesieve. So this build change is not very local.

AFAIK, boost has multiprecision ints - although yes, I'd fully understand that adding boost as a dependency for primecount is not much fun...

**Comment by mkoeppe** [comment]
> **Hence I have given up and primecount simply cannot be compiled with `-std=c++*` (because this disables the GNU extensions which primecount requires for 128-bit integers) and you should use `-std=gnu++*` instead** (or use neither `-std=c++*` nor `-std=gnu++*` in which case `-std=gnu++*` will be used by default).

This means that users cannot install primecount from source out of the box in a conda environment.

**Comment by mkoeppe** [comment]
> [...] So it seems to me that it is possible to change the `CXXFLAGS` when building a package/library for conda [...]

We are not in the business of building a conda package. We are trying to build `primecount` in the role of a user *in* a conda environment.

**Comment by kimwalisch** [comment]
> This means that users cannot install primecount from source out of the box in a conda environment.

I am sorry, but in order to safely support the ```-std=c++*``` option in primecount I would have to reimplement the entire C++ standard library with support for 128-bit integers. This is unfeasible. I have also read the GCC source code to find if I can abuse some macro to force enabling 128-bit integer support in the STL, but I could not find any.

If you really need to be able to compile primecount with ```-std=c++*``` then 128-bit integer support must be disabled in primecount. For GCC & Clang this can be achieved using (I have tested this, all tests passed successfully):

```
cmake .. -DCMAKE_CXX_FLAGS="-U__SIZEOF_INT128__"
```

**Comment by mkoeppe** [comment]
> If this is useful to sagemath I can modify primecount's build system to automatically turn off 128-bit integer support when compiling with `-std=c++*` (without the `-U__SIZEOF_INT128__` hack)

I think this would make sense.

**Comment by kimwalisch** [comment]
> If this is useful to sagemath I can modify primecount's build system to automatically turn off 128-bit integer support when compiling with `-std=c++*` (without the `-U__SIZEOF_INT128__` hack)

I have now implemented this feature, I think this feature will provide value to other users as well. The CMake configure step now checks if the C++ compiler and the C++ standard library support 128-bit integers. If not, support 128-bit integers will be disabled automatically. If the user has specified the ```-std=c++*``` command-line option then a warning message will be displayed which explains that 128-bit integer support has been disabled because of this flag:

```bash
$ CXXFLAGS="-std=c++17" cmake ..
-- The CXX compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/msys64/mingw64/bin/c++.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test int128
-- Performing Test int128 - Failed
-- Performing Test int128_with_cpp11
-- Performing Test int128_with_cpp11 - Failed
CMake Warning at CMakeLists.txt:196 (message):
  Your usage of -std=c++* disables 128-bit integer support in primecount,
  primecount will only support numbers <= 2^63.  Use -std=gnu++* instead to
  enable 128-bit integer support (or omit both -std=c++* and -std=gnu++*).
  ...
```

If you want to use this code you can generate a patch against primecount-7.2 using:

```bash
cd primecount
git diff v7.2 ab54277838a1a79f32d8c052c76f380fdff88286 > primecount-std-cpp-support.patch
```

What about this pull request? Should I merge it now, or will you commit more changes to it?

**Comment by mkoeppe** [comment]
> What about this pull request? Should I merge it now

Yes, it's complete

**Comment by mkoeppe** [comment]
> ```shell
>   Your usage of -std=c++* disables 128-bit integer support in primecount,
>   primecount will only support numbers <= 2^63.  Use -std=gnu++* instead to
>   enable 128-bit integer support (or omit both -std=c++* and -std=gnu++*).
>   ...
> ```
This is a good informative message, thanks

**Pull request merged**
