### PR TITLE
set minimal version of external primesieve

### PR DESCRIPTION
**Pull request by dimpase**
At the moment    one has  [find_package(primesieve REQUIRED)](https://github.com/kimwalisch/primecount/blob/4d33e82a13ef51db4670b34e93d41862c0f3ea5c/CMakeLists.txt#L270] - any version will be accepted. However, some distributions still carry very old primesieve, and one doesn't want them.

### CODE REVIEW

**Comment by kimwalisch** [comment]
I try very hard to not break primesieve's API and primecount should work fine even with old primesieve versions. I think the last primesieve API break was in version 6.0 from 2017 (in version 7.0 there was an ABI break no API break).

CMake documentation: https://cmake.org/cmake/help/latest/command/find_package.html

I don't fully understand CMake's find_package version handling. Doesn't your change tie primecount to primesieve-7.6? This would be pretty annoying i.e. for every new important primesive release (e.g. due to bug fixes) I would have to also do a new primecount release (just to increase the primesieve version number in primecount's CMakeLists.txt).

**Comment by mkoeppe** [comment]
It sounds like `find_package(primesieve 7 REQUIRED)` should then be used

**Comment by dimpase** [comment]
> tie primecount to primesieve-7.x

OK, let's try if this works. (Not all upstreams get cmake right, e.g. debian stable doesn't install cmake config files for primesieve - although they fixed it in unstable).

**Comment by dimpase** [comment]
If it doesn't, then `7.0` would work.

**Comment by kimwalisch** [comment]
I have read up on version pinning, here is my conclusion:

Version pinning of libraries is useful if your package manager (e.g. Npm, Cargo, ...) automatically downloads the libraries your project depends on from the Internet. This way, if someone releases a backwards incompatible library version with a new major version the build of your project won't fail.

CMake's ```find_package()``` on the other hand does not automatically download the specified library version from the Internet. Hence a if new major version of primesieve is released on a bleeding edge Linux distro and you try to build primecount on that distro, the build will simply fail. However the same would have happened without version pinning, since the new primesieve API is backwards incompatible, the compilation of primecount would also simply fail.

I have read the ```CMakeLists.txt``` of many other C/C++ projects (e.g. [curl](https://github.com/curl/curl/blob/master/CMakeLists.txt), [symengine](https://github.com/symengine/symengine/blob/master/CMakeLists.txt)) and allmost none of these projects use version pinning with ```find_package()```. Furthermore primesieve's API is very stable at this point in time, the last API break was nearly 5 years ago and I will try very hard not to break primesieve's API going forward. primecount also uses just a tiny fraction of primesieve's API, it is likely that primecount would compile and run just fine (primecount has an extensive test suite that will catch any libprimesieve issues) even with new primesieve versions with a backwards incompatible API.

I personally think pinning primesieve's version number is not needed (my preference is to follow CMake best practices of other C/C++ projects), **but I am willing to add it if you have a particular use case that requires this feature?**

**Comment by dimpase** [comment]
It's not version "pinning", it's specifyng the minimal version. E.g. the current branch builds fine with primesieve 7.6 installed.

**Comment by dimpase** [comment]
The purpose of the PR is to guard against building primecount with an outdated system-wide primesieve. Originally I thought that "outdated" means "<7.6", but the current change makes it "<7.0". I don't understand why this is controversial. 

Many projects don't sufficiently understand cmake capabilities and limitations (e.g. Debian in many ways doesn't); just looking at what they do and consider them "best practice" might not be a good idea.

**Comment by dimpase** [comment]
Some distributions still carry quite old primesieve, pre 7.0, cf. https://repology.org/project/primesieve/versions 

E.g. Ubuntu 18.04 (bionic), still widely used, has primesieve 6.3. 

When you make a new release, you may want to set the minimal version of primesieve meant to be used with it, and this PR allows you to do this (certainly, you can merely say this in README, but automated scripts aren't good in reading README :-)).

**Comment by dimpase** [comment]
> primecount has an extensive test suite that will catch any libprimesieve issues

It's not very usual to run a full testsuite of everything one installs from source, e.g. @sagemath (where primecount and primeseive are going to be standard packages in the coming release, if everything goes well - the current `prime_pi` of @sagemath is buggy) doesn't do this by default.

Further, @sagemath tries to limit the number of packages to be built from source, so in fact this PR came up from something we found on https://trac.sagemath.org/ticket/25009. 

Currently, the installation script (to be run if no new enough primecount is found on the system) we use there will try run `cmake` looking for system-wide primecount, and use it, if the version is good enough.

Due to a Debian bug, we go to some length to figure out whether system primecount is OK - it might have good enough version, but broken cmake configs. 

----

While I'm at it, let me also point out a separate Pythoh/Cython interface we'll use:
https://pypi.org/project/primecountpy/
It's mostly using the (little) code we already have in @sagemath to call primecount from Python,but we'd like to have it more modular, and we unfortunately found https://pypi.org/project/primecount/ lacking in features for our purposes.

**Comment by kimwalisch** [comment]
> While I'm at it, let me also point out a separate Pythoh/Cython interface we'll use:
https://pypi.org/project/primecountpy/

Thanks, I will add a link to the bindings section in primecount's README.

**Comment by kimwalisch** [comment]
> It's not version "pinning", it's specifyng the minimal version.

This is not correct, the cmake documentation clearly says:

* https://cmake.org/cmake/help/latest/command/find_package.html
> The [version] argument requests a version with which the package found should be compatible. There are two possible forms in which it may be specified:
> * **(EXACT) A single version** with the format major[.minor[.patch[.tweak]]], where each component is a numeric value.
> * A version range with the format versionMin...[<]versionMax where versionMin and versionMax have the same format and constraints on components being integers as the single version. By default, both end points are included. By specifying <, the upper end point will be excluded. Version ranges are only supported with CMake 3.19 or later.
>
> **The EXACT option requests that the version be matched exactly**. This option is incompatible with the specification of a version range.

The main reason I don't want this feature is that it increases my maintenance burden (and the maintenance burden of other primecount package maintainers). If a new primesieve major version is released I want primecount's build processs and test suite to figure out automatically if that new primesieve major version is compatible with primecount. I don't want to have to increase the version number manually in primecount's CMakeLists.txt and possibly have to release new primecount packages for the distros that I am maintaining just because of that pinned version number.

> The purpose of the PR is to guard against building primecount with an outdated system-wide primesieve. Originally I thought that "outdated" means "<7.6", but the current change makes it "<7.0". I don't understand why this is controversial.

As a test I have successfully built the latest primecount using primesieve-6.4 and primecount's test suite passed without any issues. primecount would also work just fine with primesieve-6.0, however primesieve-6.0 to 6.3 are missing ```find_package()``` support, so even pinning the version number won't help in this case. As I have mentioned before primesieve API is very stable at this point in time it is likely that there won't be any API breaks within this decade.

This feature is not needed, it deteriorates my workflow and I cannot see any use case that it would meaningfully improve.

**Comment by dimpase** [comment]
On Sun, 28 Nov 2021, 08:56 Kim Walisch, ***@***.***> wrote:

> It's not version "pinning", it's specifyng the minimal version.
>
> This is not correct, the cmake documentation clearly says:
>
>    - https://cmake.org/cmake/help/latest/command/find_package.html
>
> The [version] argument requests a version with which the package found
> should be compatible. There are two possible forms in which it may be
> specified:
>
>    - *(EXACT) A single version* with the format
>    major[.minor[.patch[.tweak]]], where each component is a numeric value.
>
>
Sorry, but you are reading the docs incorrectly - only if you add EXACT it
will request the exact version match.

Otherwise it's the minimal required version. Releasing versions with bigger
version numbers don't increase burden on maintenance, contrary to what you
claim.

Run a test yourself just in case. I repeat that I tested this PR in a
variety of settings, and it works as I explained, not the way you claim.

**Comment by dimpase** [comment]
Here is a quick test, showing that your reading of the manual is not correct.
Here I have latest primesieve installed in /usr/local, then I take the latest primecount source (so at least 7.6) and apply the patch in in this PR:
```
$ git diff | cat
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5b82faac..f7608a64 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -267,7 +267,7 @@ if(BUILD_LIBPRIMESIEVE)
     set(BUILD_MANPAGE "${COPY_BUILD_MANPAGE}" CACHE BOOL "Regenerate man page using a2x" FORCE)
     set(BUILD_TESTS "${COPY_BUILD_TESTS}" CACHE BOOL "Build test programs" FORCE)
 else()
-    find_package(primesieve REQUIRED)
+    find_package(primesieve 7 REQUIRED)
 endif()
 
 # Testing ############################################################
dima@hilbert /tmp/primecount $ cmake -DBUILD_LIBPRIMESIEVE=OFF .
-- The CXX compiler identification is GNU 11.2.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test libdivide_branchfree
-- Performing Test libdivide_branchfree - Success
-- Performing Test OpenMP
-- Performing Test OpenMP - Success
-- Performing Test mpopcnt
-- Performing Test mpopcnt - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/primecount
```
So all is fine and ready to build.
Now, let's change the version there to 8, and try running cmake again:
```
dima@hilbert /tmp/primecount $ git diff | cat
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5b82faac..20c13c21 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -267,7 +267,7 @@ if(BUILD_LIBPRIMESIEVE)
     set(BUILD_MANPAGE "${COPY_BUILD_MANPAGE}" CACHE BOOL "Regenerate man page using a2x" FORCE)
     set(BUILD_TESTS "${COPY_BUILD_TESTS}" CACHE BOOL "Build test programs" FORCE)
 else()
-    find_package(primesieve REQUIRED)
+    find_package(primesieve 8 REQUIRED)
 endif()
 
 # Testing ############################################################
dima@hilbert /tmp/primecount $ cmake -DBUILD_LIBPRIMESIEVE=OFF .
CMake Error at CMakeLists.txt:270 (find_package):
  Could not find a configuration file for package "primesieve" that is
  compatible with requested version "8".

  The following configuration files were considered but not accepted:

    /usr/local/lib64/cmake/primesieve/primesieveConfig.cmake, version: 7.7



-- Configuring incomplete, errors occurred!
See also "/tmp/primecount/CMakeFiles/CMakeOutput.log".
```

So as long as the version of `primesieve` is not lower than the one in `find_package()`, it's all fine.

**Comment by dimpase** [comment]
Finally, let's see the difference `EXACT` makes:
```
dima@hilbert /tmp/primecount $ git diff | cat
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 5b82faac..07f665c2 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -267,7 +267,7 @@ if(BUILD_LIBPRIMESIEVE)
     set(BUILD_MANPAGE "${COPY_BUILD_MANPAGE}" CACHE BOOL "Regenerate man page using a2x" FORCE)
     set(BUILD_TESTS "${COPY_BUILD_TESTS}" CACHE BOOL "Build test programs" FORCE)
 else()
-    find_package(primesieve REQUIRED)
+	find_package(primesieve 7 EXACT REQUIRED)
 endif()
 
 # Testing ############################################################
dima@hilbert /tmp/primecount $ cmake -DBUILD_LIBPRIMESIEVE=OFF .
CMake Error at CMakeLists.txt:270 (find_package):
  Could not find a configuration file for package "primesieve" that exactly
  matches requested version "7".

  The following configuration files were considered but not accepted:

    /usr/local/lib64/cmake/primesieve/primesieveConfig.cmake, version: 7.7



-- Configuring incomplete, errors occurred!
See also "/tmp/primecount/CMakeFiles/CMakeOutput.log".
```

All as documented by cmake...

**Pull request closed without merging**
